---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--config=./pyproject.toml']
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.ya?ml$
