services:
  app:
    build: ./backend
    container_name: mealwise_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - dev_db
  dev_db:
    image: postgres:15.14
    container_name: dev_db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - mealwise-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bob"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mealwise-dev-data:
