services:
  db:
    image: postgres:15.14
    container_name: db_test
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env.test
    volumes:
      - mealwise-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mealwise-test-data:
