---
name: Meal Planner Tests
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.14
        env:
          POSTGRES_USER: ${{ secrets.TEST_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Check formatting with black
        uses: psf/black@25.9.0
        with:
          src: "."
          options: "--verbose"
      - name: Create env file
        run: |
          cd backend
          echo "POSTGRES_USER=${{ secrets.TEST_USER }}" > .env.test
          echo "POSTGRES_PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env.test
          echo "POSTGRES_DB=${{ env.TEST_DB }}" >> .env.test
          echo "TEST_DB_URL=${{ secrets.TEST_DB_URL }}" >> .env.test
          echo "ENV=test" >> .env.test
      - name: Run unit tests
        run: |
          cd backend/tests
          pytest
